import { useEffect, useRef, useState } from "react";
import { motion } from "motion/react";
import { ArchiveRestore, Clipboard, Download, Eye, EyeOff, FileKey2, Folder, History, KeyRound, LockKeyhole, Pin, Plus, Save, Search, ShieldCheck, Trash2, Upload } from "lucide-react";
import { ApiError, apiClient } from "@/lib/client/api";
import { decryptBackup, decryptVaultValue, deriveVaultKey, encryptBackup, encryptVaultValue, generatePassword, randomSalt } from "@/lib/client/vault-crypto";
import type { ConfirmOptions, ToastKind } from "../types";

type ItemType = "note" | "password" | "checklist";
type Envelope = { title: string; type: ItemType; tags: string[]; folder: string; username?: string; url?: string };
type Secret = { body: string; password?: string };
type VaultItem = { id: string; envelope: string; content?: string; version: number; pinned: boolean; deletedAt?: string; createdAt: string; updatedAt: string };
type ViewItem = VaultItem & { meta: Envelope };
type VaultConfig = { salt: string; checkCipher: string; iterations: number };
type Version = { id: number; envelope: string; content: string; version: number; createdAt: string };

interface NotesWorkspaceProps { active: boolean; askConfirm: (options: ConfirmOptions) => Promise<boolean>; notify: (kind: ToastKind, message: string, duration?: number) => number; requestStepUp: () => Promise<boolean> }
const EMPTY_META: Envelope = { title: "", type: "note", tags: [], folder: "" };
const EMPTY_SECRET: Secret = { body: "" };

export function NotesWorkspace({ active, askConfirm, notify, requestStepUp }: NotesWorkspaceProps) {
  const keyRef = useRef<CryptoKey | null>(null); const saveTimer = useRef<number | null>(null); const activityTimer = useRef<number | null>(null); const importRef = useRef<HTMLInputElement>(null);
  const [config, setConfig] = useState<VaultConfig | null>(null); const [vaultPassword, setVaultPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState("");
  const [unlocked, setUnlocked] = useState(false); const [items, setItems] = useState<ViewItem[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null);
  const [meta, setMeta] = useState<Envelope>(EMPTY_META); const [secret, setSecret] = useState<Secret>(EMPTY_SECRET); const [baseVersion, setBaseVersion] = useState(0);
  const [query, setQuery] = useState(""); const [tagText, setTagText] = useState(""); const [revealed, setRevealed] = useState(false); const [trash, setTrash] = useState(false);
  const [dirty, setDirty] = useState(false); const [saving, setSaving] = useState(false); const [status, setStatus] = useState("Đã lưu"); const [error, setError] = useState<string | null>(null);
  const [versions, setVersions] = useState<Version[]>([]); const [showVersions, setShowVersions] = useState(false); const [backupPassword, setBackupPassword] = useState("");
  const selected = items.find(item => item.id === selectedId) ?? null;
  const filtered = items.filter(item => `${item.meta.title} ${item.meta.folder} ${item.meta.tags.join(" ")} ${item.meta.username || ""} ${item.meta.url || ""}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));

  const vaultRequest = async <T,>(path: string, options?: Parameters<typeof apiClient.request>[1]): Promise<T> => {
    try { return await apiClient.request<T>(path, options); }
    catch (caught) { if (caught instanceof ApiError && caught.status === 428 && await requestStepUp()) return apiClient.request<T>(path, options); throw caught; }
  };
  const lock = () => { keyRef.current = null; setUnlocked(false); setItems([]); setSelectedId(null); setMeta(EMPTY_META); setSecret(EMPTY_SECRET); setVaultPassword(""); setRevealed(false); };
  const resetActivity = () => { if (!unlocked) return; if (activityTimer.current) window.clearTimeout(activityTimer.current); activityTimer.current = window.setTimeout(lock, 5 * 60_000); };
  useEffect(() => { if (!active) { const timer = window.setTimeout(lock, 0); return () => window.clearTimeout(timer); } }, [active]);
  useEffect(() => { if (!unlocked) return; const events = ["pointerdown", "keydown"] as const; events.forEach(name => window.addEventListener(name, resetActivity)); resetActivity(); return () => { events.forEach(name => window.removeEventListener(name, resetActivity)); if (activityTimer.current) window.clearTimeout(activityTimer.current); }; }, [unlocked]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);

  const loadConfig = async () => { setError(null); try { const result = await vaultRequest<{ configured: boolean; config?: VaultConfig }>("/api/vault/config"); setConfig(result.config ?? null); } catch (caught) { setError(caught instanceof Error ? caught.message : "Không thể mở két"); } };
  useEffect(() => { if (active && !unlocked) { const timer = window.setTimeout(() => void loadConfig(), 0); return () => window.clearTimeout(timer); } }, [active, unlocked]); // eslint-disable-line react-hooks/exhaustive-deps
  const loadList = async (key: CryptoKey, showTrash = trash) => { const result = await vaultRequest<{ items: VaultItem[] }>(`/api/vault/items?trash=${showTrash}`); const decrypted = await Promise.all(result.items.map(async item => ({ ...item, meta: await decryptVaultValue<Envelope>(item.envelope, key, `item:${item.id}:envelope`) }))); setItems(decrypted); return decrypted; };
  const setup = async () => { if (vaultPassword.length < 12 || vaultPassword !== confirmPassword) return setError("Mật khẩu két phải có ít nhất 12 ký tự và hai lần nhập phải khớp."); try { const salt = randomSalt(); const iterations = 600_000; const key = await deriveVaultKey(vaultPassword, salt, iterations); const checkCipher = await encryptVaultValue({ ok: true }, key, "vault-check"); await vaultRequest("/api/vault/config", { method: "POST", body: { salt, iterations, checkCipher } }); keyRef.current = key; setConfig({ salt, iterations, checkCipher }); setUnlocked(true); setVaultPassword(""); setConfirmPassword(""); await migrateLegacy(key); await loadList(key); notify("success", "Đã tạo két zero-knowledge."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Không thể tạo két"); } };
  const migrateLegacy = async (key: CryptoKey) => { const legacy = await vaultRequest<{ notes: Array<{ id: string; title: string; content: string; pinned: boolean }> }>("/api/vault/legacy"); for (const note of legacy.notes) { const id = crypto.randomUUID(); await vaultRequest("/api/vault/items", { method: "POST", body: { clientId: id, envelope: await encryptVaultValue({ title: note.title, type: "note", tags: ["migrated"], folder: "Ghi chú cũ" } satisfies Envelope, key, `item:${id}:envelope`), content: await encryptVaultValue({ body: note.content } satisfies Secret, key, `item:${id}:content`), pinned: note.pinned } }); await vaultRequest(`/api/vault/legacy/${note.id}`, { method: "DELETE" }); } if (legacy.notes.length) notify("success", `Đã chuyển ${legacy.notes.length} ghi chú cũ sang két zero-knowledge.`); };
  const unlock = async () => { if (!config) return; try { const key = await deriveVaultKey(vaultPassword, config.salt, config.iterations); await decryptVaultValue(config.checkCipher, key, "vault-check"); keyRef.current = key; setUnlocked(true); setVaultPassword(""); await migrateLegacy(key); await loadList(key); } catch { keyRef.current = null; setUnlocked(false); setError("Mật khẩu két không đúng hoặc dữ liệu đã hỏng."); } };

  const selectItem = async (item: ViewItem) => { if (dirty && !window.confirm("Ghi chú đang có thay đổi chưa lưu. Tiếp tục và bỏ thay đổi?")) return; setSelectedId(item.id); setMeta(item.meta); setTagText(item.meta.tags.join(", ")); setBaseVersion(item.version); setRevealed(false); setDirty(false); setError(null); setVersions([]); const result = await vaultRequest<{ item: VaultItem }>(`/api/vault/items/${item.id}`); setSecret(await decryptVaultValue<Secret>(result.item.content!, keyRef.current!, `item:${item.id}:content`)); };
  const newItem = (type: ItemType = "note") => { setSelectedId(null); setMeta({ ...EMPTY_META, type }); setSecret(EMPTY_SECRET); setTagText(""); setBaseVersion(0); setDirty(false); setRevealed(type !== "password"); setVersions([]); };
  const mutate = (nextMeta: Envelope, nextSecret = secret) => { setMeta(nextMeta); setSecret(nextSecret); setDirty(true); setStatus("Chưa lưu"); };
  const save = async (automatic = false) => { if (!meta.title.trim() || !keyRef.current || saving) return; setSaving(true); setError(null); try { const normalized = { ...meta, title: meta.title.trim(), tags: tagText.split(",").map(value => value.trim()).filter(Boolean).slice(0, 20) }; const id = selectedId || crypto.randomUUID(); const envelope = await encryptVaultValue(normalized, keyRef.current, `item:${id}:envelope`); const content = await encryptVaultValue(secret, keyRef.current, `item:${id}:content`); const result = await vaultRequest<{ item: VaultItem }>(selectedId ? `/api/vault/items/${id}` : "/api/vault/items", { method: selectedId ? "PUT" : "POST", body: { clientId: selectedId ? undefined : id, envelope, content, pinned: selected?.pinned || false, ...(selectedId ? { version: baseVersion } : {}) } }); const view = { ...result.item, meta: normalized }; setItems(previous => [view, ...previous.filter(item => item.id !== view.id)]); setSelectedId(view.id); setBaseVersion(view.version); setMeta(normalized); setDirty(false); setStatus(automatic ? "Đã tự lưu" : "Đã lưu"); if (!automatic) notify("success", "Đã lưu vào két."); } catch (caught) { setStatus("Lỗi lưu"); setError(caught instanceof Error ? caught.message : "Không thể lưu"); } finally { setSaving(false); } };
  useEffect(() => { if (!dirty || !selectedId || !meta.title.trim()) return; if (saveTimer.current) window.clearTimeout(saveTimer.current); saveTimer.current = window.setTimeout(() => void save(true), 1200); return () => { if (saveTimer.current) window.clearTimeout(saveTimer.current); }; }, [dirty, meta, secret, tagText, selectedId]); // eslint-disable-line react-hooks/exhaustive-deps
  const togglePin = async () => { if (!selected) return; setItems(previous => previous.map(item => item.id === selected.id ? { ...item, pinned: !item.pinned } : item)); setDirty(true); };
  const trashItem = async () => { if (!selected || !await askConfirm({ title: "Chuyển vào thùng rác", message: `Chuyển “${selected.meta.title}” vào thùng rác 30 ngày?`, danger: true, confirmLabel: "Chuyển vào thùng rác" })) return; await vaultRequest(`/api/vault/items/${selected.id}`, { method: "DELETE" }); setItems(previous => previous.filter(item => item.id !== selected.id)); newItem(); };
  const changeTrash = async () => { const next = !trash; setTrash(next); newItem(); await loadList(keyRef.current!, next); };
  const restore = async (item: ViewItem) => { await vaultRequest(`/api/vault/items/${item.id}/restore`, { method: "POST" }); setItems(previous => previous.filter(value => value.id !== item.id)); notify("success", "Đã khôi phục."); };
  const purge = async (item: ViewItem) => { if (!await askConfirm({ title: "Xóa vĩnh viễn", message: `Xóa “${item.meta.title}” vĩnh viễn?`, danger: true, requiredText: "XOA", confirmLabel: "Xóa vĩnh viễn" })) return; await vaultRequest(`/api/vault/items/${item.id}/purge`, { method: "DELETE" }); setItems(previous => previous.filter(value => value.id !== item.id)); };
  const loadVersions = async () => { if (!selected) return; const result = await vaultRequest<{ versions: Version[] }>(`/api/vault/items/${selected.id}/versions`); setVersions(result.versions); setShowVersions(true); };
  const restoreVersion = async (version: Version) => { if (!selected) return; const result = await vaultRequest<{ item: VaultItem }>(`/api/vault/items/${selected.id}`, { method: "PUT", body: { envelope: version.envelope, content: version.content, pinned: selected.pinned, version: selected.version } }); const nextMeta = await decryptVaultValue<Envelope>(version.envelope, keyRef.current!, `item:${selected.id}:envelope`); const nextSecret = await decryptVaultValue<Secret>(version.content, keyRef.current!, `item:${selected.id}:content`); setMeta(nextMeta); setSecret(nextSecret); setBaseVersion(result.item.version); setItems(previous => previous.map(item => item.id === selected.id ? { ...result.item, meta: nextMeta } : item)); setShowVersions(false); };
  const copySecret = async (value: string, label: string) => { await navigator.clipboard.writeText(value); notify("success", `${label} đã sao chép; clipboard sẽ được xóa sau 30 giây.`, 5000); window.setTimeout(() => navigator.clipboard.writeText("").catch(() => undefined), 30_000); };
  const quickCopyPassword = async (item: ViewItem) => {
    try {
      const result = await vaultRequest<{ item: VaultItem }>(`/api/vault/items/${item.id}`);
      const itemSecret = await decryptVaultValue<Secret>(result.item.content!, keyRef.current!, `item:${item.id}:content`);
      if (!itemSecret.password) return setError(`“${item.meta.title}” chưa có mật khẩu.`);
      await copySecret(itemSecret.password, `Mật khẩu “${item.meta.title}”`);
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Không thể sao chép mật khẩu"); }
  };
  const exportVault = async () => { if (!backupPassword || !keyRef.current) return setError("Nhập mật khẩu riêng cho file backup."); const source = [...await loadRaw(false), ...await loadRaw(true)]; const plain = await Promise.all(source.map(async item => ({ meta: await decryptVaultValue<Envelope>(item.envelope, keyRef.current!, `item:${item.id}:envelope`), secret: await decryptVaultValue<Secret>((await vaultRequest<{ item: VaultItem }>(`/api/vault/items/${item.id}`)).item.content!, keyRef.current!, `item:${item.id}:content`), pinned: item.pinned, deleted: Boolean(item.deletedAt) }))); const blob = new Blob([JSON.stringify(await encryptBackup({ items: plain }, backupPassword))], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `nodeshell-vault-${new Date().toISOString().slice(0, 10)}.encrypted.json`; link.click(); URL.revokeObjectURL(link.href); setBackupPassword(""); };
  const loadRaw = async (isTrash: boolean) => (await vaultRequest<{ items: VaultItem[] }>(`/api/vault/items?trash=${isTrash}`)).items;
  const importVault = async (file: File) => { if (!backupPassword || !keyRef.current) return setError("Nhập mật khẩu của file backup trước."); try { const backup = await decryptBackup(JSON.parse(await file.text()), backupPassword) as { items?: Array<{ meta: Envelope; secret: Secret; pinned: boolean }> }; let count = 0; for (const item of backup.items || []) { const id = crypto.randomUUID(); await vaultRequest("/api/vault/items", { method: "POST", body: { envelope: await encryptVaultValue(item.meta, keyRef.current, `item:${id}:envelope`), content: await encryptVaultValue(item.secret, keyRef.current, `item:${id}:content`), pinned: item.pinned, clientId: id } }); count++; } await loadList(keyRef.current); notify("success", `Đã nhập ${count} mục.`); } catch (caught) { setError(caught instanceof Error ? caught.message : "Không thể nhập backup"); } };

  if (!unlocked) return <motion.div key="vault-lock" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="workspace-screen flex h-full items-center justify-center overflow-y-auto p-4"><div className="app-panel w-full max-w-md p-6"><LockKeyhole className="mx-auto h-10 w-10 text-amber-300" /><h2 className="mt-4 text-center text-xl font-bold text-white">{config ? "Mở két ghi chú" : "Khởi tạo két riêng"}</h2><p className="mt-2 text-center text-xs leading-5 text-slate-500">Mật khẩu két chỉ được xử lý trong trình duyệt và không thể khôi phục nếu bạn quên.</p><div className="mt-6 space-y-3"><input type="password" value={vaultPassword} onChange={event => setVaultPassword(event.target.value)} placeholder="Mật khẩu két" autoFocus className="w-full rounded-lg border border-white/10 bg-black/30 px-3 py-3 text-sm text-white" />{!config && <input type="password" value={confirmPassword} onChange={event => setConfirmPassword(event.target.value)} placeholder="Nhập lại mật khẩu két" className="w-full rounded-lg border border-white/10 bg-black/30 px-3 py-3 text-sm text-white" />}{error && <p className="text-xs text-rose-300">{error}</p>}<button type="button" onClick={() => void (config ? unlock() : setup())} className="w-full rounded-lg bg-amber-400 py-3 text-sm font-bold text-slate-950">{config ? "Mở khóa" : "Tạo két zero-knowledge"}</button></div></div></motion.div>;

  return <motion.div key="notes-tab" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} className="workspace-screen h-full w-full overflow-y-auto p-4 sm:p-6"><div className="mx-auto max-w-7xl space-y-4">
    <header className="workspace-heading flex flex-col gap-3 sm:flex-row sm:items-end"><div className="mr-auto"><p className="app-kicker">Zero-knowledge personal vault</p><h2 className="mt-1 text-xl font-bold uppercase tracking-wider text-white">Két Ghi Chú</h2><p className="mt-1 font-mono text-xs text-slate-500">Tự khóa sau 5 phút, nội dung chỉ giải mã khi mở</p></div><div className="flex flex-wrap gap-2"><button onClick={() => newItem("note")} className="rounded-lg bg-amber-400 px-3 py-2 text-xs font-bold text-slate-950"><Plus className="mr-1 inline h-4 w-4" />Ghi chú</button><button onClick={() => newItem("password")} className="rounded-lg bg-violet-400 px-3 py-2 text-xs font-bold text-slate-950"><KeyRound className="mr-1 inline h-4 w-4" />Mật khẩu</button><button onClick={() => void changeTrash()} className="rounded-lg border border-white/10 px-3 py-2 text-xs"><Trash2 className="mr-1 inline h-4 w-4" />{trash ? "Ghi chú" : "Thùng rác"}</button><button onClick={lock} className="rounded-lg border border-rose-400/20 px-3 py-2 text-xs text-rose-300"><LockKeyhole className="mr-1 inline h-4 w-4" />Khóa</button></div></header>
    <div className="flex items-center gap-2 rounded-xl border border-emerald-400/15 bg-emerald-400/5 px-4 py-3 text-xs text-emerald-300"><ShieldCheck className="h-4 w-4" />Server chỉ lưu ciphertext. Khóa giải mã chỉ tồn tại trong tab này.</div>{error && <div className="rounded-xl border border-rose-500/20 bg-rose-500/5 p-3 text-xs text-rose-300">{error}</div>}
    <div className="grid gap-4 lg:grid-cols-[330px_minmax(0,1fr)]"><aside className="app-panel h-fit overflow-hidden"><div className="p-3"><label className="flex items-center gap-2 rounded-lg border border-white/10 bg-black/20 px-3"><Search className="h-4 w-4 text-slate-600" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Tìm tiêu đề, tag, thư mục..." className="w-full bg-transparent py-2.5 text-xs outline-none" /></label></div><div className="max-h-[60vh] divide-y divide-white/5 overflow-auto">{filtered.map(item => <div key={item.id} className={`flex items-center ${selectedId === item.id ? "bg-amber-400/7" : ""}`}><button onClick={() => void selectItem(item)} className="min-w-0 flex-1 p-4 text-left"><div className="flex gap-2"><FileKey2 className="h-4 w-4 text-amber-300" /><div className="min-w-0"><p className="truncate text-sm font-semibold text-white">{item.meta.title}</p><p className="mt-1 truncate text-[10px] text-slate-600">{item.meta.folder || item.meta.type} {item.meta.tags.length ? `· ${item.meta.tags.join(", ")}` : ""}</p></div>{item.pinned && <Pin className="ml-auto h-3 w-3 fill-amber-300 text-amber-300" />}</div></button>{!trash && item.meta.type === "password" && <button type="button" title="Sao chép nhanh mật khẩu" aria-label={`Sao chép nhanh mật khẩu ${item.meta.title}`} onClick={() => void quickCopyPassword(item)} className="mr-2 rounded-lg border border-violet-400/20 bg-violet-400/5 p-2 text-violet-300 transition hover:bg-violet-400/15"><Clipboard className="h-4 w-4" /></button>}{trash && <div className="flex pr-2"><button title="Khôi phục" onClick={() => void restore(item)} className="p-2 text-emerald-300"><ArchiveRestore className="h-4 w-4" /></button><button title="Xóa vĩnh viễn" onClick={() => void purge(item)} className="p-2 text-rose-300"><Trash2 className="h-4 w-4" /></button></div>}</div>)}{!filtered.length && <p className="p-10 text-center text-xs text-slate-600">Không có mục nào.</p>}</div></aside>
      <section className="app-panel overflow-hidden"><div className="flex flex-wrap items-center gap-2 border-b border-white/8 p-4"><span className="mr-auto text-[10px] text-slate-500">{status}{saving ? "..." : ""}</span>{selected && <><button onClick={() => void togglePin()} className="rounded border border-white/10 px-2 py-1.5 text-xs"><Pin className="mr-1 inline h-3 w-3" />Ghim</button><button onClick={() => void loadVersions()} className="rounded border border-white/10 px-2 py-1.5 text-xs"><History className="mr-1 inline h-3 w-3" />Phiên bản</button><button onClick={() => void trashItem()} className="rounded border border-rose-400/20 px-2 py-1.5 text-xs text-rose-300"><Trash2 className="mr-1 inline h-3 w-3" />Xóa</button></>}<button onClick={() => void save()} disabled={!meta.title.trim()} className="rounded bg-sky-400 px-3 py-1.5 text-xs font-bold text-slate-950"><Save className="mr-1 inline h-3.5 w-3.5" />Lưu</button></div>
        <div className="grid gap-4 p-4 sm:grid-cols-2"><Field label="Tiêu đề"><input value={meta.title} onChange={event => mutate({ ...meta, title: event.target.value })} maxLength={200} /></Field><Field label="Loại"><select value={meta.type} onChange={event => mutate({ ...meta, type: event.target.value as ItemType })}><option value="note">Ghi chú</option><option value="password">Mật khẩu</option><option value="checklist">Checklist</option></select></Field><Field label="Thư mục"><input value={meta.folder} onChange={event => mutate({ ...meta, folder: event.target.value })} placeholder="Công việc / Máy chủ" /></Field><Field label="Nhãn, cách nhau dấu phẩy"><input value={tagText} onChange={event => { setTagText(event.target.value); setDirty(true); }} placeholder="production, quan trọng" /></Field>{meta.type === "password" && <><Field label="Tên đăng nhập"><div className="flex"><input value={meta.username || ""} onChange={event => mutate({ ...meta, username: event.target.value })} /><CopyButton onClick={() => void copySecret(meta.username || "", "Tên đăng nhập")} /></div></Field><Field label="URL"><input value={meta.url || ""} onChange={event => mutate({ ...meta, url: event.target.value })} /></Field><Field label="Mật khẩu"><div className="flex"><input type={revealed ? "text" : "password"} value={secret.password || ""} onChange={event => mutate(meta, { ...secret, password: event.target.value })} /><button onClick={() => setRevealed(value => !value)} className="border border-white/10 px-2">{revealed ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button><CopyButton onClick={() => void copySecret(secret.password || "", "Mật khẩu")} /></div></Field><Field label="Tạo mật khẩu"><button onClick={() => mutate(meta, { ...secret, password: generatePassword(24, true) })} className="w-full rounded border border-violet-400/20 bg-violet-400/5 p-2 text-xs text-violet-300"><KeyRound className="mr-1 inline h-4 w-4" />Tạo 24 ký tự mạnh</button></Field></>}<label className="sm:col-span-2 text-[10px] font-bold uppercase tracking-wider text-slate-500">Nội dung<textarea value={secret.body} onChange={event => mutate(meta, { ...secret, body: event.target.value })} className="mt-2 min-h-72 w-full rounded-xl border border-white/10 bg-[#07101a] p-4 font-mono text-sm normal-case text-slate-200 outline-none" /></label></div>
      </section></div>
    <section className="app-panel flex flex-col gap-3 p-4 sm:flex-row sm:items-end"><Field label="Mật khẩu file backup"><input type="password" value={backupPassword} onChange={event => setBackupPassword(event.target.value)} placeholder="Khác mật khẩu két nếu có thể" /></Field><button onClick={() => void exportVault()} className="rounded-lg border border-white/10 px-3 py-2 text-xs"><Download className="mr-1 inline h-4 w-4" />Xuất mã hóa</button><button onClick={() => importRef.current?.click()} className="rounded-lg border border-white/10 px-3 py-2 text-xs"><Upload className="mr-1 inline h-4 w-4" />Nhập backup</button><input ref={importRef} type="file" accept="application/json" className="hidden" onChange={event => { const file = event.target.files?.[0]; if (file) void importVault(file); event.target.value = ""; }} /><span className="ml-auto text-[10px] text-slate-600"><Folder className="mr-1 inline h-3 w-3" />Backup được mã hóa lại phía trình duyệt</span></section>
    {showVersions && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4"><div className="app-modal w-full max-w-lg p-5"><h3 className="font-bold text-white">Lịch sử phiên bản</h3><div className="mt-4 max-h-96 divide-y divide-white/5 overflow-auto">{versions.map(version => <div key={version.id} className="flex items-center justify-between py-3 text-xs"><span>Phiên bản {version.version} · {new Date(version.createdAt).toLocaleString("vi-VN")}</span><button onClick={() => void restoreVersion(version)} className="text-amber-300">Khôi phục</button></div>)}{!versions.length && <p className="py-8 text-center text-slate-600">Chưa có phiên bản cũ.</p>}</div><button onClick={() => setShowVersions(false)} className="mt-4 w-full rounded border border-white/10 py-2 text-xs">Đóng</button></div></div>}
  </div></motion.div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block min-w-0 text-[10px] font-bold uppercase tracking-wider text-slate-500">{label}<div className="mt-2 [&_input]:w-full [&_input]:rounded-lg [&_input]:border [&_input]:border-white/10 [&_input]:bg-[#09111d] [&_input]:px-3 [&_input]:py-2.5 [&_input]:text-xs [&_input]:normal-case [&_input]:text-white [&_select]:w-full [&_select]:rounded-lg [&_select]:border [&_select]:border-white/10 [&_select]:bg-[#09111d] [&_select]:px-3 [&_select]:py-2.5 [&_select]:text-xs [&_select]:normal-case">{children}</div></label>; }
function CopyButton({ onClick }: { onClick: () => void }) { return <button type="button" title="Sao chép" onClick={onClick} className="border border-white/10 px-2 text-slate-400"><Clipboard className="h-4 w-4" /></button>; }
