"use client";

import { useEffect, useState } from "react";
import { Check, FilePlus2, LockKeyhole, Plus, Search, Table2, Trash2, X } from "lucide-react";
import { apiClient } from "@/lib/client/api";
import type { Note } from "../types";

type NotesResponse = { success: true; notes: Note[] };
type NoteTable = NonNullable<Note["table"]>;
const emptyTable = (): NoteTable => ({ columns: ["Mục", "Thông tin"], rows: [["", ""]] });

export function NotesWorkspace({ notify }: { notify: (kind: "success" | "error" | "info", message: string) => void }) {
  const [notes, setNotes] = useState<Note[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null);
  const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [table, setTable] = useState<NoteTable | undefined>();
  const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const selected = notes.find((note) => note.id === selectedId);
  const visibleNotes = notes.filter((note) => `${note.title} ${note.content} ${note.table?.rows.flat().join(" ") || ""}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  const openNote = (note: Note) => { setSelectedId(note.id); setTitle(note.title); setContent(note.content); setTable(note.table); };
  const newNote = () => { setSelectedId(null); setTitle(""); setContent(""); setTable(undefined); };
  const updateTable = (next: NoteTable) => setTable(next);

  useEffect(() => { apiClient.request<NotesResponse>("/api/notes").then(({ notes }) => { setNotes(notes); if (notes[0]) openNote(notes[0]); }).catch((error: Error) => notify("error", error.message)).finally(() => setLoading(false));
  // Initial load only; notify is recreated by the dashboard.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function save() {
    if (!title.trim() && !content.trim() && !table?.columns.length) return notify("info", "Nhập tiêu đề, nội dung hoặc tạo bảng trước khi lưu.");
    setSaving(true);
    try { const response = await apiClient.request<{ note: Note }>("/api/notes" + (selectedId ? `/${selectedId}` : ""), { method: selectedId ? "PUT" : "POST", body: { title, content, table } }); setNotes((items) => [response.note, ...items.filter((item) => item.id !== response.note.id)]); openNote(response.note); notify("success", "Đã lưu ghi chú mã hóa."); }
    catch (error) { notify("error", error instanceof Error ? error.message : "Không thể lưu ghi chú."); } finally { setSaving(false); }
  }
  async function remove() { if (!selectedId || !selected || !window.confirm(`Xóa ghi chú “${selected.title || "Không tiêu đề"}”?`)) return; try { await apiClient.request(`/api/notes/${selectedId}`, { method: "DELETE" }); const next = notes.filter((note) => note.id !== selectedId); setNotes(next); if (next[0]) openNote(next[0]); else newNote(); notify("success", "Đã xóa ghi chú."); } catch (error) { notify("error", error instanceof Error ? error.message : "Không thể xóa ghi chú."); } }

  return <div className="workspace-screen h-full w-full overflow-hidden p-3 sm:p-6"><div className="mx-auto flex h-full max-w-7xl flex-col overflow-hidden rounded-2xl border border-white/10 bg-slate-950/45 shadow-2xl shadow-black/20">
    <header className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 px-4 py-4 sm:px-6"><div><div className="flex items-center gap-2 text-emerald-300"><LockKeyhole className="h-4 w-4" /><span className="app-kicker">Private vault</span></div><h2 className="mt-2 text-xl font-semibold text-white">Sổ ghi chú</h2><p className="mt-1 text-xs text-slate-500">Ghi chú và bảng dữ liệu được mã hóa AES-256-GCM.</p></div><button type="button" onClick={newNote} className="inline-flex items-center gap-2 rounded-lg border border-sky-400/25 bg-sky-400/10 px-3 py-2 text-xs font-semibold text-sky-200 transition hover:bg-sky-400/20"><FilePlus2 className="h-4 w-4" />Ghi chú mới</button></header>
    <div className="grid min-h-0 flex-1 lg:grid-cols-[minmax(320px_.8fr)_1.2fr]"><aside className="min-h-0 overflow-auto border-b border-white/10 p-3 lg:border-r lg:border-b-0"><label className="relative mb-3 block"><Search className="pointer-events-none absolute left-3 top-2.5 h-3.5 w-3.5 text-slate-500" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm tiêu đề, nội dung, bảng..." className="w-full rounded-lg border border-white/10 bg-white/5 py-2 pl-9 pr-3 text-xs text-slate-200 outline-none placeholder:text-slate-600" /></label><div className="overflow-hidden rounded-xl border border-white/10"><div className="grid grid-cols-[1fr_78px] border-b border-white/10 bg-white/[.035] px-3 py-2 text-[9px] font-bold uppercase tracking-wider text-slate-500"><span>Ghi chú</span><span>Cập nhật</span></div>{loading ? <p className="p-4 text-xs text-slate-500">Đang tải...</p> : visibleNotes.map((note) => <button type="button" key={note.id} onClick={() => openNote(note)} className={`grid w-full grid-cols-[1fr_78px] gap-2 border-b border-white/6 px-3 py-3 text-left transition last:border-0 ${note.id === selectedId ? "bg-sky-400/10" : "hover:bg-white/[.035]"}`}><span className="min-w-0"><strong className="block truncate text-xs text-slate-200">{note.title || "Không tiêu đề"}</strong><em className="mt-1 block truncate text-[10px] not-italic text-slate-500">{note.table ? `${note.table.rows.length} hàng bảng · ` : ""}{note.content || "Ghi chú trống"}</em></span><time className="text-[9px] leading-4 text-slate-600">{new Date(note.updatedAt).toLocaleDateString("vi-VN")}</time></button>)}{!loading && !visibleNotes.length && <p className="p-4 text-xs text-slate-600">Không tìm thấy ghi chú.</p>}</div></aside>
      <section className="flex min-h-0 flex-col overflow-auto p-4 sm:p-6"><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Tiêu đề ghi chú" maxLength={160} className="border-0 border-b border-white/10 bg-transparent pb-3 text-lg font-semibold text-white outline-none placeholder:text-slate-600" /><textarea value={content} onChange={(event) => setContent(event.target.value)} placeholder="Nội dung, mật khẩu, hướng dẫn hoặc việc cần nhớ..." maxLength={20000} className="mt-4 min-h-32 resize-y bg-transparent font-mono text-sm leading-6 text-slate-300 outline-none placeholder:text-slate-700" />
        <div className="mt-5 border-t border-white/10 pt-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="flex items-center gap-2 text-slate-200"><Table2 className="h-4 w-4 text-sky-300" /><strong className="text-sm">Bảng dữ liệu</strong></div><p className="mt-1 text-[10px] text-slate-600">Lưu danh sách tài khoản, mã, máy chủ hoặc việc cần làm.</p></div>{!table ? <button type="button" onClick={() => setTable(emptyTable())} className="inline-flex items-center gap-1.5 rounded-lg border border-sky-400/25 px-2.5 py-1.5 text-xs text-sky-200 hover:bg-sky-400/10"><Plus className="h-3.5 w-3.5" />Tạo bảng</button> : <button type="button" onClick={() => setTable(undefined)} className="inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-xs text-rose-300 hover:bg-rose-500/10"><X className="h-3.5 w-3.5" />Bỏ bảng</button>}</div>
          {table && <div className="mt-4 overflow-x-auto rounded-xl border border-white/10"><table className="min-w-full border-collapse text-xs"><thead><tr>{table.columns.map((column, columnIndex) => <th key={columnIndex} className="min-w-36 border-b border-r border-white/10 bg-white/[.035] p-0 last:border-r-0"><input value={column} onChange={(event) => updateTable({ ...table, columns: table.columns.map((value, index) => index === columnIndex ? event.target.value : value) })} placeholder={`Cột ${columnIndex + 1}`} className="w-full bg-transparent px-3 py-2.5 font-semibold text-slate-300 outline-none placeholder:text-slate-600" /></th>)}<th className="w-9 border-b border-white/10 bg-white/[.035]" /></tr></thead><tbody>{table.rows.map((row, rowIndex) => <tr key={rowIndex}>{row.map((cell, columnIndex) => <td key={columnIndex} className="border-r border-b border-white/8 p-0 last:border-r-0"><input value={cell} onChange={(event) => updateTable({ ...table, rows: table.rows.map((values, index) => index === rowIndex ? values.map((value, cellIndex) => cellIndex === columnIndex ? event.target.value : value) : values) })} className="w-full bg-transparent px-3 py-2.5 text-slate-400 outline-none focus:bg-sky-400/5" /></td>)}<td className="border-b border-white/8 text-center"><button type="button" onClick={() => updateTable({ ...table, rows: table.rows.filter((_, index) => index !== rowIndex) })} className="p-2 text-slate-600 hover:text-rose-300" aria-label="Xóa hàng"><Trash2 className="h-3.5 w-3.5" /></button></td></tr>)}</tbody></table><div className="flex gap-2 border-t border-white/10 p-2"><button type="button" onClick={() => updateTable({ ...table, rows: [...table.rows, table.columns.map(() => "")] })} disabled={table.rows.length >= 100} className="inline-flex items-center gap-1 rounded px-2 py-1 text-[10px] text-sky-200 hover:bg-sky-400/10"><Plus className="h-3 w-3" />Thêm hàng</button><button type="button" onClick={() => updateTable({ columns: [...table.columns, `Cột ${table.columns.length + 1}`], rows: table.rows.map((row) => [...row, ""]) })} disabled={table.columns.length >= 12} className="inline-flex items-center gap-1 rounded px-2 py-1 text-[10px] text-sky-200 hover:bg-sky-400/10"><Plus className="h-3 w-3" />Thêm cột</button></div></div>}</div>
        <footer className="mt-5 flex items-center justify-between border-t border-white/10 pt-4"><span className="text-[10px] text-slate-600">{content.length.toLocaleString("vi-VN")} / 20.000 ký tự</span><div className="flex gap-2">{selectedId && <button type="button" onClick={() => void remove()} className="inline-flex items-center gap-2 rounded-lg px-3 py-2 text-xs text-rose-300 hover:bg-rose-500/10"><Trash2 className="h-4 w-4" />Xóa</button>}<button type="button" disabled={saving} onClick={() => void save()} className="inline-flex items-center gap-2 rounded-lg bg-emerald-400 px-3 py-2 text-xs font-bold text-slate-950 hover:bg-emerald-300 disabled:opacity-60"><Check className="h-4 w-4" />{saving ? "Đang lưu" : "Lưu ghi chú"}</button></div></footer></section>
    </div>
  </div></div>;
}
