import { ArrowLeft, ChevronRight, Database, Folder, Save, Table2, X } from "lucide-react";
import type { Dispatch, SetStateAction } from "react";
import type { FileMetadata, FileSnapshot, SqliteBrowserItem, SqliteColumn, SqliteRecordModal, TrashItem, UserRole } from "./types";

interface ResourceModalsProps {
  metadata: { value: FileMetadata | null; onChange: (value: FileMetadata) => void; onClose: () => void; onSave: () => void };
  trash: { open: boolean; items: TrashItem[]; selectedIds: string[]; onToggle: (id: string) => void; onClose: () => void; onRestore: () => void; onDelete: () => void; onEmpty: () => void };
  snapshots: { open: boolean; items: FileSnapshot[]; path: string; role?: UserRole; onClose: () => void; onDownload: (id: string, name: string) => void; onRestore: (id: string) => void; onDelete: (id: string) => void };
  serviceLogs: { value: { unit: string; logs: string } | null; onClose: () => void };
  record: { modal: SqliteRecordModal; table: string; values: Record<string, unknown>; columns: SqliteColumn[]; loading: boolean; onValuesChange: Dispatch<SetStateAction<Record<string, unknown>>>; onClose: () => void; onSave: () => void };
  browser: { open: boolean; path: string; parent: string | null; root: string; items: SqliteBrowserItem[]; onPathChange: (path: string) => void; onBrowse: (path: string) => void; onSelect: (path: string) => void; onClose: () => void };
}

export function ResourceModals({ metadata, trash, snapshots, serviceLogs, record, browser }: ResourceModalsProps) {
  return <>
    {metadata.value && <MetadataModal metadata={metadata.value} onChange={metadata.onChange} onClose={metadata.onClose} onSave={metadata.onSave} />}
    {trash.open && <TrashModal {...trash} />}
    {snapshots.open && <SnapshotsModal {...snapshots} />}
    {serviceLogs.value && <ServiceLogsModal value={serviceLogs.value} onClose={serviceLogs.onClose} />}
    {record.modal && <RecordModal {...record} modal={record.modal} />}
    {browser.open && <BrowserModal {...browser} />}
  </>;
}

function MetadataModal({ metadata, onChange, onClose, onSave }: { metadata: FileMetadata; onChange: (value: FileMetadata) => void; onClose: () => void; onSave: () => void }) {
  return <div className="fixed inset-0 z-50 bg-black/75 backdrop-blur-sm flex items-center justify-center p-4"><div className="app-modal w-full max-w-md p-5 space-y-4"><div className="flex"><h4 className="font-bold text-white">Quyền và sở hữu</h4><button onClick={onClose} className="ml-auto"><X className="w-4 h-4" /></button></div><p className="text-xs font-mono truncate">{metadata.path}</p><label className="block text-xs">Mode<input value={metadata.mode} onChange={(event) => onChange({ ...metadata, mode: event.target.value })} className="mt-1 w-full bg-black border border-white/10 rounded p-2 font-mono" /></label><div className="grid grid-cols-2 gap-3"><label className="text-xs">UID<input type="number" value={metadata.uid} onChange={(event) => onChange({ ...metadata, uid: Number(event.target.value) })} className="mt-1 w-full bg-black border border-white/10 rounded p-2" /></label><label className="text-xs">GID<input type="number" value={metadata.gid} onChange={(event) => onChange({ ...metadata, gid: Number(event.target.value) })} className="mt-1 w-full bg-black border border-white/10 rounded p-2" /></label></div><button onClick={onSave} className="w-full bg-blue-600 rounded py-2 text-sm text-white">Lưu quyền</button></div></div>;
}

function TrashModal({ items, selectedIds, onToggle, onClose, onRestore, onDelete, onEmpty }: ResourceModalsProps["trash"]) {
  return <div className="fixed inset-0 z-50 bg-black/75 backdrop-blur-sm flex items-center justify-center p-4"><div className="app-modal w-full max-w-2xl max-h-[80vh] overflow-auto p-5 space-y-4"><div className="flex items-center"><h4 className="font-bold text-white">Thùng rác</h4><button onClick={onClose} className="ml-auto"><X className="w-4 h-4" /></button></div>{items.length === 0 ? <p className="text-sm text-slate-500">Thùng rác trống.</p> : items.map((item) => <label key={item.id} className="flex gap-3 p-3 border border-white/5 rounded text-xs"><input type="checkbox" checked={selectedIds.includes(item.id)} onChange={() => onToggle(item.id)} /><span className="flex-1 min-w-0"><span className="block text-white truncate">{item.name || item.originalPath.split("/").pop()}</span><span className="text-slate-500 font-mono break-all">{item.originalPath}</span></span><span className="text-slate-500">{item.deletedAt ? new Date(item.deletedAt).toLocaleString() : ""}</span></label>)}<div className="flex flex-wrap gap-2"><button disabled={!selectedIds.length} onClick={onRestore} className="px-3 py-2 bg-emerald-600 rounded text-xs disabled:opacity-30">Khôi phục</button><button disabled={!selectedIds.length} onClick={onDelete} className="px-3 py-2 bg-red-600 rounded text-xs disabled:opacity-30">Xóa vĩnh viễn</button><button onClick={onEmpty} className="ml-auto px-3 py-2 bg-red-950 text-red-300 rounded text-xs">Dọn sạch</button></div></div></div>;
}

function SnapshotsModal({ items, path, role, onClose, onDownload, onRestore, onDelete }: ResourceModalsProps["snapshots"]) {
  return <div className="fixed inset-0 z-50 bg-black/75 backdrop-blur-sm flex items-center justify-center p-4"><div className="app-modal w-full max-w-4xl max-h-[85vh] overflow-auto p-5 space-y-4"><div className="flex items-center gap-3"><Database className="w-5 h-5 text-amber-400" /><div><h4 className="font-bold text-white">Lịch sử snapshot</h4><p className="text-[10px] text-slate-500 font-mono">{path || "Tất cả tệp"} · {items.length} phiên bản</p></div><button onClick={onClose} className="ml-auto"><X className="w-4 h-4" /></button></div>{items.length === 0 ? <p className="py-12 text-center text-sm text-slate-500">Chưa có snapshot phù hợp.</p> : <div className="space-y-2">{items.map((snapshot) => <div key={snapshot.id} className="grid md:grid-cols-[1fr_180px_auto] gap-3 items-center p-3 rounded border border-white/5 bg-black/40"><div className="min-w-0"><div className="text-xs text-white truncate">{snapshot.originalPath}</div><div className="mt-1 text-[10px] text-slate-500 font-mono">{snapshot.reason} · {(snapshot.size / 1024).toFixed(1)} KB · mode {snapshot.mode.toString(8)}</div><code className="block mt-1 text-[9px] text-slate-600 truncate" title={snapshot.checksum}>SHA-256 {snapshot.checksum}</code></div><div className="text-[10px] text-slate-500">{new Date(snapshot.createdAt).toLocaleString()}</div><div className="flex gap-2"><button onClick={() => onDownload(snapshot.id, snapshot.originalPath.split("/").pop() || "snapshot")} className="text-xs text-blue-400">Tải</button>{role !== "viewer" && <><button onClick={() => onRestore(snapshot.id)} className="text-xs text-emerald-400">Khôi phục</button><button onClick={() => onDelete(snapshot.id)} className="text-xs text-red-400">Xóa</button></>}</div></div>)}</div>}</div></div>;
}

function ServiceLogsModal({ value, onClose }: { value: { unit: string; logs: string }; onClose: () => void }) {
  return <div className="fixed inset-0 z-50 bg-black/80 flex items-center justify-center p-4"><div className="w-full max-w-5xl max-h-[85vh] flex flex-col rounded-xl border border-white/10 bg-[#111116] p-5 gap-4"><div className="flex items-center"><div><h4 className="font-bold text-white">Journal: {value.unit}</h4><p className="text-[10px] text-slate-500">200 dòng gần nhất</p></div><button onClick={onClose} className="ml-auto"><X className="w-4 h-4" /></button></div><pre className="flex-1 overflow-auto whitespace-pre-wrap break-words bg-black border border-white/5 rounded p-4 text-[11px] leading-relaxed text-slate-300 font-mono">{value.logs || "Không có log."}</pre></div></div>;
}

function RecordModal({ modal, table, values, columns, loading, onValuesChange, onClose, onSave }: ResourceModalsProps["record"] & { modal: NonNullable<SqliteRecordModal> }) {
  return <div className="fixed inset-0 z-50 bg-black/85 flex items-center justify-center p-4"><div className="w-full max-w-2xl max-h-[85vh] overflow-y-auto rounded-xl border border-emerald-500/20 bg-[#0d1110] shadow-2xl"><div className="sticky top-0 z-[1] flex items-center gap-3 p-5 border-b border-white/10 bg-[#0d1110]"><Table2 className="w-5 h-5 text-emerald-400" /><div><h4 className="font-bold text-white">{modal.mode === "add" ? "Thêm bản ghi" : "Chỉnh sửa bản ghi"}</h4><p className="mt-1 text-[10px] text-slate-500 font-mono">{table} · nhập chính xác <span className="text-emerald-400">NULL</span> để lưu giá trị null</p></div><button onClick={onClose} className="ml-auto"><X className="w-4 h-4" /></button></div><div className="grid sm:grid-cols-2 gap-3 p-5">{Object.entries(values).map(([column, value]) => <label key={column} className="block text-[10px] uppercase tracking-wider text-slate-500"><span className="flex items-center gap-2">{column}{columns.find((item) => item.name === column)?.primaryKey && <span className="rounded bg-amber-500/10 px-1.5 py-0.5 text-[8px] text-amber-400">PK</span>}</span><textarea value={value === null ? "NULL" : typeof value === "object" ? JSON.stringify(value) : String(value)} onChange={(event) => onValuesChange((current) => ({ ...current, [column]: event.target.value }))} rows={2} className="mt-1.5 w-full resize-y rounded border border-white/10 bg-black p-2.5 text-xs font-mono normal-case tracking-normal text-white outline-none focus:border-emerald-500/40" /></label>)}</div><div className="sticky bottom-0 flex justify-end gap-2 p-4 border-t border-white/10 bg-[#0d1110]"><button onClick={onClose} className="px-4 py-2 text-xs border border-white/10 rounded">Hủy</button><button onClick={onSave} disabled={loading} className="flex items-center gap-2 px-4 py-2 text-xs bg-emerald-500 text-black font-bold rounded disabled:opacity-40"><Save className="w-3.5 h-3.5" />{modal.mode === "add" ? "Thêm bản ghi" : "Lưu thay đổi"}</button></div></div></div>;
}

function BrowserModal({ path, parent, root, items, onPathChange, onBrowse, onSelect, onClose }: ResourceModalsProps["browser"]) {
  return <div className="fixed inset-0 z-50 bg-black/85 flex items-center justify-center p-3 sm:p-4"><div className="w-full max-w-4xl max-h-[88vh] flex flex-col rounded-xl border border-emerald-500/20 bg-[#0d1110] shadow-2xl overflow-hidden"><div className="flex items-start gap-3 p-5 border-b border-white/10"><Folder className="w-5 h-5 text-emerald-400" /><div><h4 className="font-bold text-white">Mở SQLite có sẵn</h4><p className="mt-1 text-[10px] text-slate-500 font-mono">Duyệt filesystem từ {root || "root"} · chỉ hiện file SQLite hợp lệ</p></div><button onClick={onClose} className="ml-auto"><X className="w-4 h-4" /></button></div><form onSubmit={(event) => { event.preventDefault(); onBrowse(path); }} className="flex gap-2 p-3 border-b border-white/10"><button type="button" disabled={!parent} onClick={() => parent && onBrowse(parent)} title="Thư mục cha" className="p-2.5 rounded border border-white/10 disabled:opacity-30"><ArrowLeft className="w-4 h-4" /></button><input value={path} onChange={(event) => onPathChange(event.target.value)} placeholder="/var/lib/app" className="min-w-0 flex-1 bg-black border border-white/10 focus:border-emerald-500/50 outline-none rounded px-3 py-2 text-xs text-white font-mono" /><button type="submit" className="px-4 py-2 rounded bg-white/5 border border-white/10 text-xs">Đi tới</button></form><div className="flex-1 min-h-64 overflow-y-auto divide-y divide-white/5">{items.map((item) => <button key={item.path} onClick={() => item.type === "directory" ? onBrowse(item.path) : onSelect(item.path)} className="w-full flex items-center gap-3 p-3 sm:px-5 text-left hover:bg-white/[0.03]"><span className={`p-2 rounded ${item.type === "directory" ? "bg-blue-500/10 text-blue-400" : "bg-emerald-500/10 text-emerald-400"}`}>{item.type === "directory" ? <Folder className="w-4 h-4" /> : <Database className="w-4 h-4" />}</span><span className="min-w-0 flex-1"><span className="block text-xs text-white truncate">{item.name}</span><span className="block mt-1 text-[9px] text-slate-600 font-mono truncate">{item.path}</span></span>{item.type === "database" ? <span className="text-[9px] text-slate-500">{((item.size || 0) / 1024).toFixed(1)} KB</span> : <ChevronRight className="w-4 h-4 text-slate-700" />}</button>)}{items.length === 0 && <div className="p-12 text-center text-xs text-slate-600">Thư mục trống hoặc không có file SQLite hợp lệ.</div>}</div><div className="flex items-center justify-between gap-3 p-3 border-t border-white/10 text-[9px] text-slate-600 font-mono"><span className="truncate">Root: {root}</span><button onClick={onClose} className="px-3 py-1.5 text-xs border border-white/10 rounded text-slate-300">Đóng</button></div></div></div>;
}
